"""empty message

Revision ID: bc8f736c1ba9
Revises: f61fd1b907c6
Create Date: 2026-06-26 00:57:28.303913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8f736c1ba9'
down_revision: Union[str, Sequence[str], None] = 'f61fd1b907c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('pending', 'ordered', 'shipped', 'delivered', name='orderstatus'), nullable=False, server_default="pending"))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
